### ISSUE TITLE
Fatal Exception: java.lang.IllegalThreadStateException: Thread already started

### ISSUE THREAD

**Issue by ImDroidGuy** [FinweLtd/orion360-sdk-basic-examples-android#2]
Fatal Exception: java.lang.IllegalThreadStateException: Thread already started
at java.lang.Thread.checkNotStarted(Thread.java:849)
at java.lang.Thread.start(Thread.java:1059)
at fi.finwe.orion360.OrionVideoPlayerAsync.initializePlayer(OrionVideoPlayerAsync.java:108)
at fi.finwe.orion360.OrionVideoView.onContextStatusChanged(OrionVideoView.java:579)
at fi.finwe.orion360.OrionSurfaceView.onSurfaceChanged(OrionSurfaceView.java:477)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1520)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)

DEVICE : SAMSUNG GALAXY NOTE 3
OS : 5

**Comment by trantako** [comment]
This might be related to how your OrionVideoView is initialized and used.

Please provide more information, such as:
- Does this problem occur every time or occasionally
- Does this occur on all test devices or only on some models
- What actions user performs before the problem occurs

A code sample that demonstrates the issue would be very helpful.

**Comment by ImDroidGuy** [comment]
- This crash occur on a particular device occasionally

- No issues on other devices
